--DDL - DATA DEFINITION LANGUAGE

CREATE DATABASE Health_Clinic_TD

USE Health_Clinic_TD

CREATE TABLE Clinica(

IdClinica INT PRIMARY KEY IDENTITY,
NomeFantasia VARCHAR(50)NOT NULL,
RazaoSocial VARCHAR(150)NOT NULL,
CNPJ CHAR(14) NOT NULL,
Endereco VARCHAR(200) NOT NULL,
HorarioAbertura TIME,
HoraFechamento TIME

);


CREATE TABLE TipoUsuario(

IdTipoUsuario INT PRIMARY KEY IDENTITY,
TituloTipoUsuario VARCHAR(50) NOT NULL

);

CREATE TABLE Especialidade(

IdEspecialidade INT PRIMARY KEY IDENTITY,
TituloEspecialidade VARCHAR(100) NOT NULL

);


CREATE TABLE Usuario(

IdUsuario INT PRIMARY KEY IDENTITY,
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)NOT NULL,
Nome VARCHAR(100)NOT NULL,
Email VARCHAR(100)NOT NULL,
Senha VARCHAR(50)NOT NULL,
DataNascimento DATE
);

CREATE TABLE Paciente(

IdPaciente INT PRIMARY KEY IDENTITY,
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL,
RG CHAR(9)NOT NULL,
CPF CHAR(11)NOT NULL,
Endereco VARCHAR(100) NOT NULL,
Telefone VARCHAR(9)NOT NULL
);

CREATE TABLE Medico(

IdMedico INT PRIMARY KEY IDENTITY,
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)NOT NULL,
IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade)NOT NULL,
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL,
CRM VARCHAR(8)NOT NULL

);


CREATE TABLE Consulta(

IdConsulta INT PRIMARY KEY IDENTITY,
IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico)NOT NULL,
IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente)NOT NULL,
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)NOT NULL,
Descricao VARCHAR(250),
HoraConsulta TIME,
DataConsulta DATE

);




CREATE TABLE Comentario(

IdComentario INT PRIMARY KEY IDENTITY,
IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente),
IdConsulta INT FOREIGN KEY REFERENCES Consulta(IdConsulta),
Descricao VARCHAR(250)

);

